[package]
name = "peeky"
version = "0.0.0"
edition = "2024"
authors = ["dmyTRUEk"]

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
minifb = { version = "0.28.0", default-features = false, features = ["wayland"] }
